
variables:
    COMPOSER_ALLOW_SUPERUSER: 1
    COMPOSER_NO_INTERACTION: 1
    CACHE_COMPRESSION_LEVEL: "fastest"
    FF_USE_FASTZIP: 1

cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
        - vendor/
stages:
    - build
    - code
    - test

install: # Installation des dépendances du projet
    stage: build
    script:
        - composer install --prefer-dist --no-ansi --no-interaction --no-progress
    tags:
        - php81
        - composer

code-fixer: # Vérification du code PHP
    stage: code
    dependencies:
        - install
    script:
        - vendor/bin/php-cs-fixer fix --diff --dry-run
    tags:
        - php81
        - composer

lint:twig: # Vérification du Twig
    stage: code
    dependencies:
        - install
    script:
        - bin/console lint:twig templates
    tags:
        - php81
        - composer

lint:yaml: # Vérification du YAML
    stage: code
    dependencies:
        - install
    script:
        - bin/console lint:yaml config
    tags:
        - php81
        - composer

phpunit: # Exécution des tests
    stage: test
    dependencies:
        - install
    script:
        - composer test
    tags:
        - php81
        - composer
